In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
x = tf.Variable(3.0)

In [ ]:
with tf.GradientTape() as tape:
  y = x * x

In [ ]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

In [ ]:
tape.gradient(y, x)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [ ]:
x = tf.Variable([
  [1.0, -1.0, 2.0, 4.0],
  [-2.0, 3.0, -5.0, 9.0],
  [4.0, 2.0, 3.0, 9.0],
  [1.0, 5.0, 6.0, 3.0],

])
t = 30.0

In [ ]:
with tf.GradientTape() as tape:
  a = tf.nn.max_pool2d(tf.reshape(x, (1, 4, 4, 1)), ksize=2, strides=2, padding="VALID")
  b = tf.reduce_sum(a)
  error = 0.5 * (b - t) ** 2

In [ ]:
a

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[3.],
         [9.]],

        [[5.],
         [9.]]]], dtype=float32)>

In [ ]:
b

<tf.Tensor: shape=(), dtype=float32, numpy=26.0>

In [ ]:
error

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [ ]:
tape.gradient(error, [b, x])

[<tf.Tensor: shape=(), dtype=float32, numpy=-4.0>,
 <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[ 0.,  0.,  0.,  0.],
        [ 0., -4.,  0., -4.],
        [ 0.,  0.,  0., -4.],
        [ 0., -4.,  0.,  0.]], dtype=float32)>]